#include <raylib.h>
#include <iostream>
#include <vector>
#include <cmath>
#include <chrono>
#include <thread>
#include <queue>
#include <string>
#include <condition_variable>
#include <mutex>



int SCREENX = 1280;
int SCREENY = 900;
int COLUMNS = 100;
int ROWS = 100;
int WIDTH = 600;
int HEIGHT = 600;
float g = 2000;
int RADIUS = 10;
float DAMPING = 0.9;
int PASSES = 25;



int RADIUSSQUARED = RADIUS * RADIUS;
struct POINT {
	bool FIXED = false;
	Vector2 PREVIOUSPOSITION = Vector2(0, 0);
	Vector2 CURRENTPOSITION = Vector2(0, 0);

};

struct STICK {
	bool CONNECTED = true;
	POINT* POINT1 = nullptr;
	POINT* POINT2 = nullptr;
	char ALONG = NULL;

};


struct FIBER {
	int START = NULL;
	int END = NULL;
	std::string TYPE = "";
};


std::vector<std::vector<POINT>> POINTS;
std::vector<STICK> VERTICALSTICKS;
std::vector<STICK> HORIZONTALSTICKS;

int SPACINGX = WIDTH / (float)(COLUMNS - 1);
int SPACINGY = HEIGHT / (float)(ROWS - 1);

int LENGTHX = SPACINGX;
int LENGTHY = SPACINGY;

float STARTX = (SCREENX - WIDTH) / 2.0f;
float STARTY = (SCREENY - HEIGHT) / 2.0f;

std::chrono::steady_clock::time_point CURRENTTIME = std::chrono::steady_clock::now();
std::chrono::steady_clock::time_point PREVIOUSTIME;
float DELTATIME;



void InitializePointsAndSticks() {
	for (int ROW = 0; ROW < ROWS; ROW++) {
		POINTS.push_back(std::vector<POINT>{});
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			POINT POINT;
			POINT.CURRENTPOSITION.x = STARTX + COLUMN * SPACINGX;
			POINT.CURRENTPOSITION.y = STARTY + ROW * SPACINGY;
			POINT.PREVIOUSPOSITION = POINT.CURRENTPOSITION;
			if (ROW == 0) {
				POINT.FIXED = true;
			}
			POINTS[ROW].push_back(POINT);
		}
	}
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			STICK STICK;
			if (COLUMN < COLUMNS - 1) {
				STICK.POINT1 = &POINTS[ROW][COLUMN];
				STICK.POINT2 = &POINTS[ROW][COLUMN + 1];
				STICK.ALONG = 'X';
				HORIZONTALSTICKS.push_back(STICK);
			}
			if (ROW < ROWS - 1) {
				STICK.POINT1 = &POINTS[ROW][COLUMN];
				STICK.POINT2 = &POINTS[ROW + 1][COLUMN];
				STICK.ALONG = 'Y';
				VERTICALSTICKS.push_back(STICK);
			}
		}
	}

}

void Reset() {
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			POINTS[ROW][COLUMN].CURRENTPOSITION.x = STARTX + COLUMN * SPACINGX;
			POINTS[ROW][COLUMN].CURRENTPOSITION.y = STARTY + ROW * SPACINGY;
			POINTS[ROW][COLUMN].PREVIOUSPOSITION = POINTS[ROW][COLUMN].CURRENTPOSITION;
			if (ROW == 0) {
				POINTS[ROW][COLUMN].FIXED = true;
			}
		}
	}
	for (STICK& STICK : VERTICALSTICKS) {
		STICK.CONNECTED = true;
	}
	for (STICK& STICK : HORIZONTALSTICKS) {
		STICK.CONNECTED = true;
	}
}

void ApplyGravityToPoints() {
	float GRAVITY = g * DELTATIME * DELTATIME;
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			if (POINTS[ROW][COLUMN].FIXED) {
				continue;
			}
			float VELOCITYX = POINTS[ROW][COLUMN].CURRENTPOSITION.x - POINTS[ROW][COLUMN].PREVIOUSPOSITION.x;
			float VELOCITYY = POINTS[ROW][COLUMN].CURRENTPOSITION.y - POINTS[ROW][COLUMN].PREVIOUSPOSITION.y;
			Vector2 TEMPORARY = POINTS[ROW][COLUMN].CURRENTPOSITION;
			POINTS[ROW][COLUMN].CURRENTPOSITION.x += VELOCITYX * DAMPING;
			POINTS[ROW][COLUMN].CURRENTPOSITION.y += VELOCITYY * DAMPING + GRAVITY;
			POINTS[ROW][COLUMN].PREVIOUSPOSITION = TEMPORARY;

		}
	}
}

void CutSticks() {
	Vector2 MOUSEPOSITION = GetMousePosition();
	for (STICK& STICK : VERTICALSTICKS) {
		float DISTANCESQUARED = pow((MOUSEPOSITION.x - ((STICK.POINT1->CURRENTPOSITION.x + STICK.POINT2->CURRENTPOSITION.x) / 2.0)), 2) + pow((MOUSEPOSITION.y - ((STICK.POINT1->CURRENTPOSITION.y + STICK.POINT2->CURRENTPOSITION.y) / 2.0)), 2);
		if (DISTANCESQUARED <= RADIUSSQUARED) {
			STICK.CONNECTED = false;
		}
	}
	for (STICK& STICK : HORIZONTALSTICKS) {
		float DISTANCESQUARED = pow((MOUSEPOSITION.x - ((STICK.POINT1->CURRENTPOSITION.x + STICK.POINT2->CURRENTPOSITION.x) / 2.0)), 2) + pow((MOUSEPOSITION.y - ((STICK.POINT1->CURRENTPOSITION.y + STICK.POINT2->CURRENTPOSITION.y) / 2.0)), 2);
		if (DISTANCESQUARED <= RADIUSSQUARED) {
			STICK.CONNECTED = false;
		}
	}
}

void DrawSticks() {
	for (STICK& STICK : VERTICALSTICKS) {
		if (STICK.CONNECTED) {
			DrawLine(STICK.POINT1->CURRENTPOSITION.x, STICK.POINT1->CURRENTPOSITION.y, STICK.POINT2->CURRENTPOSITION.x, STICK.POINT2->CURRENTPOSITION.y, WHITE);
		}
	}
	for (STICK& STICK : HORIZONTALSTICKS) {
		if (STICK.CONNECTED) {
			DrawLine(STICK.POINT1->CURRENTPOSITION.x, STICK.POINT1->CURRENTPOSITION.y, STICK.POINT2->CURRENTPOSITION.x, STICK.POINT2->CURRENTPOSITION.y, WHITE);
		}
	}
}

std::queue<FIBER> HORIZONTALFIBERS;
std::queue<FIBER> VERTICALFIBERS;
int THREADS = std::thread::hardware_concurrency();
std::condition_variable FILL;
std::condition_variable FILLED;
std::queue<FIBER> WORK;
std::mutex WORKMUTEX;
std::vector<std::thread> THREADPOOL;
bool RUNNING = true;



void CreateHorizontalFibers() {
	for (int ROW = 0; ROW < ROWS; ROW++) {
		int START = ROW * (COLUMNS - 1);
		int END = (ROW + 1) * (COLUMNS - 1) - 1;
		FIBER FIBER;
		FIBER.START = START;
		FIBER.END = END;
		FIBER.TYPE = "HORIZONTAL";
		HORIZONTALFIBERS.push(FIBER);
	}
}

void CreateVerticalFibers() {
	for (int COL = 0; COL < COLUMNS; COL++) {
		int START = COL * (ROWS - 1);
		int END = (COL + 1) * (ROWS - 1) - 1;
		FIBER FIBER;
		FIBER.START = START;
		FIBER.END = END;
		FIBER.TYPE = "VERTICAL";
		VERTICALFIBERS.push(FIBER);
	}
}


void Pass() {
	std::unique_lock<std::mutex> WORKLOCK(WORKMUTEX);
	WORK = VERTICALFIBERS;
	FILLED.notify_all();
	FILL.wait(WORKLOCK, []() { return WORK.empty(); });
	WORK = HORIZONTALFIBERS;
	FILLED.notify_all();
	FILL.wait(WORKLOCK, []() { return WORK.empty(); });
}

void EvaluateFibers() {
	while (RUNNING) {
		std::unique_lock<std::mutex> WORKLOCK(WORKMUTEX);
		if (!WORK.empty()) {
			FIBER CURRENTFIBER = WORK.front();
			WORK.pop();
			WORKLOCK.unlock();
			if (CURRENTFIBER.TYPE == "VERTICAL") {
				int START = CURRENTFIBER.START;
				int END = CURRENTFIBER.END;
				for (START; START <= END; START++) {
					if (!VERTICALSTICKS[START].CONNECTED) {
						continue;
					}
					float DISTANCE = sqrt(pow((VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x), 2) + pow((VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y), 2));
					float CORRECTIONRATIO;
					CORRECTIONRATIO = (DISTANCE - LENGTHY) / DISTANCE;
					float DISTANCEX = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x;
					float DISTANCEY = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y;
					if (!VERTICALSTICKS[START].POINT1->FIXED && !VERTICALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO / 2;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
					else if (!VERTICALSTICKS[START].POINT1->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
					}
					else if (!VERTICALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
				}
			}
			else if (CURRENTFIBER.TYPE == "HORIZONTAL") {
				int START = CURRENTFIBER.START;
				int END = CURRENTFIBER.END;
				for (START; START <= END; START++) {
					float DISTANCE = sqrt(pow((HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x), 2) + pow((HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y), 2));
					if (!HORIZONTALSTICKS[START].CONNECTED) {
						continue;
					}
					float CORRECTIONRATIO;
					CORRECTIONRATIO = (DISTANCE - LENGTHX) / DISTANCE;
					float DISTANCEX = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x;
					float DISTANCEY = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y;
					if (!HORIZONTALSTICKS[START].POINT1->FIXED && !HORIZONTALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO / 2;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
					else if (!HORIZONTALSTICKS[START].POINT1->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
					}
					else if (!HORIZONTALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
				}
			}
		}
		else {
			FILL.notify_one();
			FILLED.wait(WORKLOCK, []() { return !WORK.empty(); });
		}
	}
}

void InitializeThreads() {
	for (int i = 0; i < THREADS - 1; i++) {
		THREADPOOL.emplace_back(std::thread(EvaluateFibers));
	}
}






int main() {

	InitializePointsAndSticks();
	CreateVerticalFibers();
	CreateHorizontalFibers();
	InitializeThreads();
	InitWindow(SCREENX, SCREENY, "Cloth Simulation");

	while (!WindowShouldClose()) {
		PREVIOUSTIME = CURRENTTIME;
		CURRENTTIME = std::chrono::steady_clock::now();
		DELTATIME = std::chrono::duration_cast<std::chrono::nanoseconds>(CURRENTTIME - PREVIOUSTIME).count() / (float)1e9;
		BeginDrawing();
		DrawFPS(10, 10);
		ClearBackground(BLACK);

		if (IsMouseButtonDown(MOUSE_RIGHT_BUTTON)) {
			Reset();
		}
		if (IsMouseButtonDown(MOUSE_LEFT_BUTTON)) {
			CutSticks();
		}
		ApplyGravityToPoints();

		for (int PASS = 0; PASS < PASSES; PASS++) {
			Pass();
		}


		DrawSticks();
		EndDrawing();
	}
	CloseWindow();
	RUNNING = false;
	FILL.notify_all();  // wake any sleeping threads
	return 0;
}