#include <raylib.h>
#include <vector>
#include <cmath>
#include <chrono>

int SCREENX = 1280;
int SCREENY = 720;
int COLUMNS = 80;
int ROWS = 80;
int WIDTH = 600;
int HEIGHT = 600;
float g = 500;
int RADIUS = 10;
float DAMPING = 0.9;
int PASSES = 10;

struct POINT {
	bool FIXED = false;
	Vector2 PREVIOUSPOSITION = Vector2(0, 0);
	Vector2 CURRENTPOSITION = Vector2(0, 0);

};

struct STICK {
	bool CONNECTED = true;
	POINT* POINT1 = nullptr;
	POINT* POINT2 = nullptr;
	char ALONG;

};

int main() {

	std::vector<std::vector<POINT>> POINTS;
	std::vector<STICK> STICKS;





	int SPACINGX = WIDTH / (float)(COLUMNS - 1);
	int SPACINGY = HEIGHT / (float)(ROWS - 1);

	int LENGTHX = SPACINGX;
	int LENGTHY = SPACINGY;

	float STARTX = (SCREENX - WIDTH) / 2.0f;
	float STARTY = (SCREENY - HEIGHT) / 2.0f;

	for (int ROW = 0; ROW < ROWS; ROW++) {
		POINTS.push_back(std::vector<POINT>{});
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			POINT POINT;
			POINT.CURRENTPOSITION.x = STARTX + COLUMN * SPACINGX;
			POINT.CURRENTPOSITION.y = STARTY + ROW * SPACINGY;
			POINT.PREVIOUSPOSITION = POINT.CURRENTPOSITION;
			if (ROW == 0) {
				POINT.FIXED = true;
			}
			POINTS[ROW].push_back(POINT);
		}
	}
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			STICK STICK;
			if (COLUMN < COLUMNS - 1) {
				STICK.POINT1 = &POINTS[ROW][COLUMN];
				STICK.POINT2 = &POINTS[ROW][COLUMN + 1];
				STICK.ALONG = 'X';
				STICKS.push_back(STICK);
			}
			if (ROW < ROWS - 1) {
				STICK.POINT1 = &POINTS[ROW][COLUMN];
				STICK.POINT2 = &POINTS[ROW + 1][COLUMN];
				STICK.ALONG = 'Y';
				STICKS.push_back(STICK);
			}
		}
	}

	InitWindow(SCREENX, SCREENY, "Cloth Simulation");
	std::chrono::steady_clock::time_point CURRENTTIME = std::chrono::steady_clock::now();
	std::chrono::steady_clock::time_point PREVIOUSTIME;

	while (!WindowShouldClose()) {
		PREVIOUSTIME = CURRENTTIME;
		CURRENTTIME = std::chrono::steady_clock::now();
		float DELTATIME = std::chrono::duration_cast<std::chrono::nanoseconds>(CURRENTTIME - PREVIOUSTIME).count() / (float)1e9;

		BeginDrawing();
		DrawFPS(10, 10);
		ClearBackground(BLACK);



		for (int ROW = 0; ROW < ROWS; ROW++) {
			for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
				if (POINTS[ROW][COLUMN].FIXED) {
					continue;
				}
				float VELOCITYX = POINTS[ROW][COLUMN].CURRENTPOSITION.x - POINTS[ROW][COLUMN].PREVIOUSPOSITION.x;
				float VELOCITYY = POINTS[ROW][COLUMN].CURRENTPOSITION.y - POINTS[ROW][COLUMN].PREVIOUSPOSITION.y;
				Vector2 TEMPORARY = POINTS[ROW][COLUMN].CURRENTPOSITION;
				POINTS[ROW][COLUMN].CURRENTPOSITION.x += VELOCITYX * DAMPING;
				POINTS[ROW][COLUMN].CURRENTPOSITION.y += VELOCITYY * DAMPING + g * pow(DELTATIME, 2);
				POINTS[ROW][COLUMN].PREVIOUSPOSITION = TEMPORARY;

			}
		}
		for (int PASS = 0; PASS < PASSES; PASS++) {

			for (STICK& STICK : STICKS) {
				float DISTANCE = sqrt(pow((STICK.POINT2->CURRENTPOSITION.x - STICK.POINT1->CURRENTPOSITION.x), 2) + pow((STICK.POINT2->CURRENTPOSITION.y - STICK.POINT1->CURRENTPOSITION.y), 2));
				if (!STICK.CONNECTED) {
					continue;
				}
				float CORRECTIONRATIO;
				if (STICK.ALONG == 'X') {
					CORRECTIONRATIO = (DISTANCE - LENGTHX) / DISTANCE;
				}
				else if (STICK.ALONG == 'Y') {
					CORRECTIONRATIO = (DISTANCE - LENGTHY) / DISTANCE;
				}
				float DISTANCEX = STICK.POINT2->CURRENTPOSITION.x - STICK.POINT1->CURRENTPOSITION.x;
				float DISTANCEY = STICK.POINT2->CURRENTPOSITION.y - STICK.POINT1->CURRENTPOSITION.y;
				if (!STICK.POINT1->FIXED && !STICK.POINT2->FIXED) {
					float CORRECTION = CORRECTIONRATIO / 2;
					STICK.POINT1->CURRENTPOSITION.x = STICK.POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
					STICK.POINT1->CURRENTPOSITION.y = STICK.POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
					STICK.POINT2->CURRENTPOSITION.x = STICK.POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
					STICK.POINT2->CURRENTPOSITION.y = STICK.POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
				}
				else if (!STICK.POINT1->FIXED) {
					float CORRECTION = CORRECTIONRATIO;
					STICK.POINT1->CURRENTPOSITION.x = STICK.POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
					STICK.POINT1->CURRENTPOSITION.y = STICK.POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
				}
				else if (!STICK.POINT2->FIXED) {
					float CORRECTION = CORRECTIONRATIO;
					STICK.POINT2->CURRENTPOSITION.x = STICK.POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
					STICK.POINT2->CURRENTPOSITION.y = STICK.POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
				}
			}
		}


		if (IsMouseButtonDown(MOUSE_LEFT_BUTTON)) {
			Vector2 MOUSEPOSITION = GetMousePosition();
			for (STICK& STICK : STICKS) {
				float DISTANCE = sqrt(pow((MOUSEPOSITION.x - ((STICK.POINT1->CURRENTPOSITION.x + STICK.POINT2->CURRENTPOSITION.x) / 2.0)), 2) + pow((MOUSEPOSITION.y - ((STICK.POINT1->CURRENTPOSITION.y + STICK.POINT2->CURRENTPOSITION.y) / 2.0)), 2));
				if (DISTANCE <= RADIUS) {
					STICK.CONNECTED = false;
				}
			}

		}


		for (STICK& STICK : STICKS) {
			if (STICK.CONNECTED) {
				DrawLine(STICK.POINT1->CURRENTPOSITION.x, STICK.POINT1->CURRENTPOSITION.y, STICK.POINT2->CURRENTPOSITION.x, STICK.POINT2->CURRENTPOSITION.y, WHITE);
			}
		}

		EndDrawing();
	}
	CloseWindow();
	return 0;
}