#include <raylib.h>
#include <iostream>
#include <vector>
#include <cmath>
#include <chrono>
#include <thread>
#include <queue>
#include <string>
#include <semaphore>



int SCREENX = 1280;
int SCREENY = 900;
constexpr int SIDE = 200;
int COLUMNS = SIDE;
int ROWS = SIDE;
int WIDTH = 600;
int HEIGHT = 600;
float g = 1000;
int RADIUS = 10;
float DAMPING = 0.98;
int PASSES = 60;
int FIBERLENGTH = 10; //Row/Column Per Fiber



int RADIUSSQUARED = RADIUS * RADIUS;
struct POINT {
	bool FIXED = false;
	Vector2 PREVIOUSPOSITION = Vector2(0, 0);
	Vector2 CURRENTPOSITION = Vector2(0, 0);

};

struct STICK {
	bool CONNECTED = true;
	POINT* POINT1 = nullptr;
	POINT* POINT2 = nullptr;
	char ALONG = NULL;

};


struct FIBER {
	int START = NULL;
	int END = NULL;
	std::string TYPE = "";
};


std::vector<POINT> POINTS;
std::vector<STICK> VERTICALSTICKS;
std::vector<STICK> HORIZONTALSTICKS;

int SPACINGX = WIDTH / (float)(COLUMNS - 1);
int SPACINGY = HEIGHT / (float)(ROWS - 1);

int LENGTHX = SPACINGX;
int LENGTHY = SPACINGY;

float STARTX = (SCREENX - WIDTH) / 2.0f;
float STARTY = (SCREENY - HEIGHT) / 2.0f;

std::chrono::steady_clock::time_point CURRENTTIME = std::chrono::steady_clock::now();
std::chrono::steady_clock::time_point PREVIOUSTIME;
float DELTATIME;



void InitializePointsAndSticks() {
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			POINT POINT;
			POINT.CURRENTPOSITION.x = STARTX + COLUMN * SPACINGX;
			POINT.CURRENTPOSITION.y = STARTY + ROW * SPACINGY;
			POINT.PREVIOUSPOSITION = POINT.CURRENTPOSITION;
			if (ROW == 0) {
				POINT.FIXED = true;
			}
			POINTS.push_back(POINT);
		}
	}
	for (int ROW = 0; ROW < ROWS; ROW++) {
		for (int COLUMN = 0; COLUMN < COLUMNS; COLUMN++) {
			STICK STICK;
			if (COLUMN < COLUMNS - 1) {
				STICK.POINT1 = &POINTS[COLUMN + ROW * COLUMNS];
				STICK.POINT2 = &POINTS[(COLUMN + 1) + ROW * COLUMNS];
				STICK.ALONG = 'X';
				HORIZONTALSTICKS.push_back(STICK);
			}
			if (ROW < ROWS - 1) {
				STICK.POINT1 = &POINTS[COLUMN + ROW * COLUMNS];
				STICK.POINT2 = &POINTS[COLUMN + (ROW + 1) * COLUMNS];
				STICK.ALONG = 'Y';
				VERTICALSTICKS.push_back(STICK);
			}
		}
	}
}



void ApplyGravityToPoints() {
	float GRAVITY = g * DELTATIME * DELTATIME;
	for (POINT& POINT : POINTS) {
		if (POINT.FIXED) {
			continue;
		}
		float VELOCITYX = POINT.CURRENTPOSITION.x - POINT.PREVIOUSPOSITION.x;
		float VELOCITYY = POINT.CURRENTPOSITION.y - POINT.PREVIOUSPOSITION.y;
		Vector2 TEMPORARY = POINT.CURRENTPOSITION;
		POINT.CURRENTPOSITION.x += VELOCITYX * DAMPING;
		POINT.CURRENTPOSITION.y += VELOCITYY * DAMPING + GRAVITY;
		POINT.PREVIOUSPOSITION = TEMPORARY;
	}
}

void CutSticks() {
	Vector2 MOUSEPOSITION = GetMousePosition();
	for (STICK& STICK : VERTICALSTICKS) {
		float DISTANCESQUARED = pow((MOUSEPOSITION.x - ((STICK.POINT1->CURRENTPOSITION.x + STICK.POINT2->CURRENTPOSITION.x) / 2.0)), 2) + pow((MOUSEPOSITION.y - ((STICK.POINT1->CURRENTPOSITION.y + STICK.POINT2->CURRENTPOSITION.y) / 2.0)), 2);
		if (DISTANCESQUARED <= RADIUSSQUARED) {
			STICK.CONNECTED = false;
		}
	}
	for (STICK& STICK : HORIZONTALSTICKS) {
		float DISTANCESQUARED = pow((MOUSEPOSITION.x - ((STICK.POINT1->CURRENTPOSITION.x + STICK.POINT2->CURRENTPOSITION.x) / 2.0)), 2) + pow((MOUSEPOSITION.y - ((STICK.POINT1->CURRENTPOSITION.y + STICK.POINT2->CURRENTPOSITION.y) / 2.0)), 2);
		if (DISTANCESQUARED <= RADIUSSQUARED) {
			STICK.CONNECTED = false;
		}
	}
}

void DrawSticks() {
	for (STICK& STICK : VERTICALSTICKS) {
		if (STICK.CONNECTED) {
			DrawLine(STICK.POINT1->CURRENTPOSITION.x, STICK.POINT1->CURRENTPOSITION.y, STICK.POINT2->CURRENTPOSITION.x, STICK.POINT2->CURRENTPOSITION.y, WHITE);
		}
	}
	for (STICK& STICK : HORIZONTALSTICKS) {
		if (STICK.CONNECTED) {
			DrawLine(STICK.POINT1->CURRENTPOSITION.x, STICK.POINT1->CURRENTPOSITION.y, STICK.POINT2->CURRENTPOSITION.x, STICK.POINT2->CURRENTPOSITION.y, WHITE);
		}
	}
}

std::vector<FIBER> HORIZONTALFIBERS;
std::vector<FIBER> VERTICALFIBERS;
int THREADS = std::thread::hardware_concurrency();
std::vector<FIBER>* WORK;
std::vector<std::thread> THREADPOOL;
std::counting_semaphore<SIDE> WORKSEMAPHORE(0);
std::binary_semaphore DONESEMAPHORE(0);
std::atomic<int> NEXTWORK;
std::atomic<int> WORKDONE;
bool RUNNING = true;



void CreateHorizontalFibers() {
	for (int ROW = 0; ROW < ROWS; ROW += FIBERLENGTH) {
		int START = ROW * (COLUMNS - 1);
		int END = (ROW + FIBERLENGTH) * (COLUMNS - 1) - 1;
		FIBER FIBER;
		FIBER.START = START;
		FIBER.END = END;
		FIBER.TYPE = "HORIZONTAL";
		HORIZONTALFIBERS.push_back(FIBER);
	}
}

void CreateVerticalFibers() {
	for (int COL = 0; COL < COLUMNS; COL += FIBERLENGTH) {
		int START = COL * (ROWS - 1);
		int END = (COL + FIBERLENGTH) * (ROWS - 1) - 1;
		FIBER FIBER;
		FIBER.START = START;
		FIBER.END = END;
		FIBER.TYPE = "VERTICAL";
		VERTICALFIBERS.push_back(FIBER);
	}
}


void Pass() {
	NEXTWORK.store(0);
	WORKDONE.store(0);
	WORK = &VERTICALFIBERS;
	WORKSEMAPHORE.release(VERTICALFIBERS.size());
	DONESEMAPHORE.acquire();
	NEXTWORK.store(0);
	WORKDONE.store(0);
	WORK = &HORIZONTALFIBERS;
	WORKSEMAPHORE.release(HORIZONTALFIBERS.size());
	DONESEMAPHORE.acquire();
}

void EvaluateFibers() {
	while (RUNNING) {
		WORKSEMAPHORE.acquire();
		int INDEX = NEXTWORK.fetch_add(1);
		if (INDEX < WORK->size()) {
			FIBER CURRENTFIBER = (*WORK)[INDEX];
			if (CURRENTFIBER.TYPE == "VERTICAL") {
				int START = CURRENTFIBER.START;
				int END = CURRENTFIBER.END;
				for (START; START <= END; START++) {
					if (!VERTICALSTICKS[START].CONNECTED) {
						continue;
					}
					float dx = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x;
					float dy = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y;
					float DISTANCE = sqrt((dx * dx) + (dy * dy));
					float CORRECTIONRATIO = (DISTANCE - LENGTHY) / DISTANCE;
					if (!VERTICALSTICKS[START].POINT1->FIXED && !VERTICALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO / 2;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x + dx * CORRECTION;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y + dy * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - dx * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - dy * CORRECTION;
					}
					else if (!VERTICALSTICKS[START].POINT1->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.x + dx * CORRECTION;
						VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT1->CURRENTPOSITION.y + dy * CORRECTION;
					}
					else if (!VERTICALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.x - dx * CORRECTION;
						VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y = VERTICALSTICKS[START].POINT2->CURRENTPOSITION.y - dy * CORRECTION;
					}
				}
			}
			else if (CURRENTFIBER.TYPE == "HORIZONTAL") {
				int START = CURRENTFIBER.START;
				int END = CURRENTFIBER.END;
				for (START; START <= END; START++) {
					float dx = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x;
					float dy = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y;
					float DISTANCE = sqrt((dx * dx) + (dy * dy));
					if (!HORIZONTALSTICKS[START].CONNECTED) {
						continue;
					}
					float CORRECTIONRATIO;
					CORRECTIONRATIO = (DISTANCE - LENGTHX) / DISTANCE;
					float DISTANCEX = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x;
					float DISTANCEY = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y;
					if (!HORIZONTALSTICKS[START].POINT1->FIXED && !HORIZONTALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO / 2;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
					else if (!HORIZONTALSTICKS[START].POINT1->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.x + DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT1->CURRENTPOSITION.y + DISTANCEY * CORRECTION;
					}
					else if (!HORIZONTALSTICKS[START].POINT2->FIXED) {
						float CORRECTION = CORRECTIONRATIO;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.x - DISTANCEX * CORRECTION;
						HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y = HORIZONTALSTICKS[START].POINT2->CURRENTPOSITION.y - DISTANCEY * CORRECTION;
					}
				}
			}
			if (WORKDONE.fetch_add(1) == WORK->size() - 1) {
				DONESEMAPHORE.release();
			}
		}
	}
}

void InitializeThreads() {
	for (int i = 0; i < THREADS - 1; i++) {
		THREADPOOL.emplace_back(std::thread(EvaluateFibers));
	}
}

void Reset() {
	POINTS.clear();
	VERTICALSTICKS.clear();
	HORIZONTALSTICKS.clear();
	InitializePointsAndSticks();
	VERTICALFIBERS.clear();
	HORIZONTALFIBERS.clear();
	CreateVerticalFibers();
	CreateHorizontalFibers();
}




int main() {
	POINTS.reserve(100000);
	InitializePointsAndSticks();
	CreateVerticalFibers();
	CreateHorizontalFibers();
	InitializeThreads();

	InitWindow(SCREENX, SCREENY, "Cloth Simulation");

	while (!WindowShouldClose()) {
		PREVIOUSTIME = CURRENTTIME;
		CURRENTTIME = std::chrono::steady_clock::now();
		DELTATIME = std::chrono::duration_cast<std::chrono::nanoseconds>(CURRENTTIME - PREVIOUSTIME).count() / (float)1e9;
		BeginDrawing();
		DrawFPS(10, 10);
		ClearBackground(BLACK);

		if (IsMouseButtonDown(MOUSE_RIGHT_BUTTON)) {
			Reset();
		}
		if (IsMouseButtonDown(MOUSE_LEFT_BUTTON)) {
			CutSticks();
		}
		ApplyGravityToPoints();

		for (int PASS = 0; PASS < PASSES; PASS++) {
			Pass();
		}


		DrawSticks();
		EndDrawing();
	}
	CloseWindow();
	RUNNING = false;
	return 0;
}